#!/bin/bash

# mkdir tmptransc/
# for i in *
#     do ffmpeg.exe -hwaccel cuda -i "$i" -map 0 -c copy -c:v libx264 -preset medium -crf "$1" "$i"_crf28."$2"
#     mv "$i"_crf28.mp4 tmptransc/
# done
allVideos=()
if [ "$1" = "all" ] && ([ "$2" = "mkv" ] || [ "$2" = "mp4" ])
    then
		for i in *."$2"
		do
			allVideos+=("$i")
		done

		# adding a ! return the list of all array indices
		for x in ${!allVideos[@]}
		do
			ffmpeg.exe -hwaccel auto -i "${allVideos[$x]}" -map 0 -c:a "$3" -c:v "$4" -rc-lookahead 40 "${allVideos[$x]%.*}".mkv
			# echo "${allVideos[$x]%.*}" # %.* removes filename extension
		done
elif [ "$1" = "help" ] || [ "$1" = "h" ] || [ -z "$1" ]
	then
	echo -e "Param list :\n1:[file] [audio codec] [video codec (add crf or qp)] \n2:[all] [mkv / mp4] [audio codec] [video codec (add crf or qp)]"
else
	ffmpeg.exe -hwaccel auto -i "$1" -map 0 -c:a "$2" -c:v "$3" -rc-lookahead 40 "$2" "${1%.*}"_"$2"qp_hevc.mkv
fi